version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: numbers-backend-dev
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
    volumes:
      - ./numbers.db:/app/numbers.db
      - ./backend:/app/backend
    networks:
      - numbers-network
    restart: unless-stopped
    command: ["uvicorn", "backend.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: numbers-frontend-dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - numbers-network
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  numbers-network:
    driver: bridge 